language: node_js
node_js: 
  - '14'
cache: yarn

install:
  - yarn install

script:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master