language: node_js
branches: 
  only:
    - master
install:
  - yarn install
cache:
  directories:
    - node_modules
    - ~/.npm
node_js: 
  - '13'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy Released"
  on:
    branch: master