language: node_js
node_js: 
  - '14'
cache: yarn

install:
  - yarn install

script:
  - yarn test
  - yarn run build

git:
  depth: 3
deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy Released"
  on:
    branch: master